settings:
  
  #База данных
  mysql:
    #Название базы
    basename: 'store'
    #Пароль
    password: 'martin'
    #Хост
    host: 'localhost:3306'
    #Пользователь
    user: 'root'
    #Таблица данных об игроке
    table-data: 'refsData'
    #Таблица данных об игроках,
    #которые использовали реферал
    table-users: 'refsUsers'
  
  #Призы
  commands:
    #Тому, кто ввел код
    sender:
      - 'eco give <user> 50'
      - 'donatemoney give <user> 10'
    #Тому, кто создал код
    target:
      - 'eco give <user> 150'
      - 'donatemoney give <user> 30'
  
  #Защита от твинков
  protection:
    #Необходимые часы игры
    time: 56
    #Необходимое количество шагов
    walk: 10000

messages:
  
  #Простые информирующие
  #сообщения
  defaults:
    
    #Помощь по командам
    help: |-
      &r
      &7Ваш реферальный код: &a<mycode> 
      &r 
      &e/ref&7 - помощь по командам
      &e/ref <code>&7 - использовать реферальный код
      &e/ref create <code>&7 - создать реферальный код
      &e/ref delete <code>&7 - удалить реферальный код
      &e/ref list [page]&7 - просмотреть список игроков
      &r 
    
    #Помощь по командам для админов
    admin-help: |-
      &c/ref admin list [user] [page]&7:
      &fПросмотреть список игроков указанного игрока.
      &fЕсли не указать, то выведет список зарегистрированных
      &fрефералок и количество использовавших ее игроков.
      &r 
      &c/ref admin delete <user>&7:
      &fУдалить реферальный код игрока.
      &r 
    
    #Игрок создал рефералку
    create: '&7Вы создали собственный реферальный код: &a<code>&7.'
    #Игрок удалил рефералку
    delete: '&7Вы удалили свой реферальный код...'
    #Сообщение об использование кода
    send:
      #Отправителю
      sender: '&7Вы успешно использовали реферальный код.'
      #Владельцу кода
      #(если оффлайн, то не отправится)
      target: '&a<user> &7использовал ваш реферальный код.'
  
  #Формат различных сообщений
  formats:
    
    #Формат /ref list и /ref admin list <user>
    list:
      - '&7Список:' #Верхняя строка
      - '&e<user> &8<status>' #Формат игрока
      
    #Формат /ref admin list
    admin-list:
      - '&7Список' #Верхняя строка
      - '&e<user>&8: &a<refs> &8<code>' #Формат игрока
  
  #Когда игрок тупит и делает то, что не должен    
  errors:
    
    #У игрока уже есть рефералка
    already-create: '&cВы уже создали собственный реферальный код.'
    #Игрок уже использовал рефералку кого-то
    already-send: '&cВы уже использовали реферальный код.'
    #Не прошел проверку IP
    ip: '&cВаши IP схожи и в целях защиты от обмана, мы не можем разрешить использование данного реферального кода.'
    #Игрок не выполнил условия
    disallow: '&cВы не отыграли &a24 &cчаса и не прошли более &a10000 &cшагов.'
    #Не найден игрок с указнным кодом
    null-target: '&cИгрок с указнным кодом не найден.'
    #Игрок не имеет реферального кода
    null-referral: '&cВы не имеете реферального кода.'
    #Длинный\короткий код
    lenght: '&cВаш код должен быть длиной в &a6 &cсимволов.'